spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_for_coder?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  profiles:
    active: local


server:
  port: 8389
  servlet:
    context-path: /ai-for-coder

# springdoc-openapi http://localhost:8389/ai-for-coder/doc.html
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      packages-to-scan: com.muzi.aiforcoder.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.muzi.aiforcoder.mapper: debug